import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap",
  preload: true,
});
const jost = localFont({
  src: [
    {
      path: "./fonts/Jost/static/Jost-Regular.ttf",
      weight: "400",
    },
    {
      path: "./fonts/Jost/static/Jost-Medium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/Jost/static/Jost-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "./fonts/Jost/static/Jost-Bold.ttf",
      weight: "700",
    },
    {
      path: "./fonts/Jost/static/Jost-ExtraBold.ttf",
      weight: "900",
    },
  ],
  display: "swap",
  variable: "--font-Jost",
  preload: true,
});

// export const metadata: Metadata = {
//   title: "koppsuisse",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={params.locale ?? "en"}>
      <body className={`${geistSans.variable} ${jost.className} antialiased`}>{children}</body>
    </html>
  );
}
